baseURL = "https://wilhelm.codes/"
languageCode = "en-us"
title = "Wilhelm Codes"
enableGitInfo = true

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Archive'
    pageRef = '/archive'
    weight = 20

[sitemap]
  changeFreq = "daily"

[params]
  description = "Slinger of nibbles, bits and bytes. Over 25 years of professional experience as a software engineer. Love making glowing rectangles go \"beep-boop\"."
  [params.author]
    email = "0xdeadbeef@devilmayco.de"
    name = "ɯlǝɥlᴉʍ"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
  [markup.highlight]
    style = "nord"
