baseURL = "https://wilhelm.codes/"
languageCode = "en-us"
title = "Wilhelm Codes"
enableGitInfo = true

[params]
  description = "Slinger of nibbles, bits and bytes. Over 25 years of professional experience as a software engineer. Love making glowing rectangles go \"beep-boop\"."
  [params.author]
    email = "0xdeadbeef@devilmayco.de"
    name = "ɯlǝɥlᴉʍ"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
  [markup.highlight]
    style = "catppuccin-mocha"
